/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/soccer_ball.glb -o Soccer.tsx 
*/

import * as THREE from "three";
import React, { JSX } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    geo1_principledshader_0: THREE.Mesh;
  };
  materials: {
    principledshader: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/soccer_ball.glb",
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.geo1_principledshader_0.geometry}
        material={materials.principledshader}
        scale={0.01}
      />
    </group>
  );
}

useGLTF.preload("/soccer_ball.glb");
