/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/heart_in_love.glb -o HeartBubble.tsx 
Author: Azamuki (https://sketchfab.com/Azamuki)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/heart-in-love-f39ce19b92e246268f4c501b72ea7d0e
Title: Heart in Love
*/

import * as THREE from "three";
import React, { JSX } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Heart_Heart_0: THREE.Mesh;
    Marble_Marble_0: THREE.Mesh;
  };
  materials: {
    Heart: THREE.MeshStandardMaterial;
    Marble: THREE.MeshPhysicalMaterial;
  };
};

export default function HeartBubble(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "./models//heart_in_love.glb",
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Heart_Heart_0.geometry}
        material={materials.Heart}
        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        scale={0.5}
      />
      <mesh
        geometry={nodes.Marble_Marble_0.geometry}
        material={materials.Marble}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.5}
      />
    </group>
  );
}

useGLTF.preload("./models/heart_in_love.glb");
